const swaggerAutogen = require('swagger-autogen')()
const outputFile = './swaggerDocs.json'
const endpointsFiles = ['./routes/authRoutes', './routes/opportunityRoutes']
const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "",
  basePath: "/api",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "authorization",
      in: "header"
    },
  },
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./server.js')
})